export const RECIVE_PETS_SUCCESS = 'RECIVE_PETS_SUCCESS';
export const RECIVE_PETS_FAILURE = 'RECIVE_PETS_FAILURE';
export const REQUEST_PETS = 'REQUEST_PETS';

export const CREATE_PETS_SUCCESS = 'CREATE_PETS_SUCCESS';
export const CREATE_PETS_FAILURE = 'CREATE_PETS_FAILURE';

export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_FAILURE = 'DELETE_PET_FAILURE';
