export const RECIVE_PETS_SUCCESS = 'RECIVE_PETS_SUCCESS';
export const RECIVE_PETS_FAILURE = 'RECIVE_PETS_FAILURE';
export const REQUEST_PETS = 'REQUEST_PETS';

export const CREATE_PETS_SUCCESS = 'CREATE_PETS_SUCCESS';
export const CREATE_PETS_FAILURE = 'CREATE_PETS_FAILURE';

export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_FAILURE = 'DELETE_PET_FAILURE';

export const RECIVE_PET_SUCCESS = 'RECIVE_PET_SUCCESS';
export const RECIVE_PET_FAILURE = 'RECIVE_PET_FAILURE';

export const EDIT_PET_SUCCESS = 'EDIT_PET_SUCCESS';
export const EDIT_PET_FAILURE = 'EDIT_PET_FAILURE';

export const EDIT_PAGE_CLEANUP = 'EDIT_PAGE_CLEANUP';